name = "portfolio-tracker-cloudflare"
compatibility_date = "2025-08-01"
pages_build_output_dir = "frontend/dist"
[[d1_databases]]
binding = "PORTFOLIO_DB"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
database_name = "portfolio_tracker_db"
